logging:
#  level:
#    root: TRACE
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure: INFO

server:
  error:
    whitelabel:
      enabled: false




spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
  profiles:
    active: @profile@
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret

