logging:
  file: log/log.log
  level:
#    root: TRACE
    org:
      springframework:
        security: TRACE
        boot:
          autoconfigure: INFO
        data.mongodb.core.MongoTemplate: DEBUG

server:
  error:
    whitelabel:
      enabled: false




spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
  profiles:
    active: @profile@


security:
  oauth2:
    client:
      client-id: client
      client-secret: secret

