logging:
  level:
    #    root: TRACE
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
server:
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library
