logging:
  level:
#    root: TRACE
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    web: debug

server:
  error:
    whitelabel:
      enabled: false

spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: library

  profiles:
    active: @profile@